version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
      - npm install -g @angular/cli
  build:
    commands:
      - echo Building project...
      - echo Build sort of started on `date`
      - ng build 
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes

cache:
  paths:
    - '/root/.npm/**/*'