
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo node modules installed
      - npm install -g @angular/cli
      - echo Angular Installed
      