version: 0.2
env:
    variables:
      CACHE_CONTROL: "86400"
      S3_BUCKET: "arn:aws:s3:::lil-shop-of-horrors"
      BUILD_FOLDER: "dist"
      BUILD_ENV: "prod"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
      - npm install -g @angular/cli
  build:
    commands:
      - echo Building project...
      - echo Build sort of started on `date`
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*
